/**
 * ═══════════════════════════════════════════════════════════
 *  LUME — End-to-End Integration Tests
 *  .lume source → compile → run JS → verify output
 * ═══════════════════════════════════════════════════════════
 */
import { describe, it } from 'node:test'
import { strict as assert } from 'node:assert'
import { tokenize } from '../../src/lexer.js'
import { parse } from '../../src/parser.js'
import { transpile } from '../../src/transpiler.js'
import { resolveEnglishFile } from '../../src/intent-resolver/index.js'
import { matchPattern } from '../../src/intent-resolver/pattern-library.js'
import { parseAppDescription, generateProjectStructure } from '../../src/intent-resolver/app-generator.js'

/* ── Helper: compile and run Lume source ── */
function compileAndRun(source, filename = '<test>') {
    const tokens = tokenize(source, filename)
    const ast = parse(tokens, filename)
    const js = transpile(ast, filename)
    const code = js.replace(/^\/\/ Generated by Lume Compiler\n\n?/, '')
    const output = []
    const origLog = console.log
    console.log = (...args) => output.push(args.join(' '))
    try {
        new Function(code)()
    } finally {
        console.log = origLog
    }
    return { js, output }
}

/* ═══ E2E: Core Language Pipeline ═══ */
describe('E2E: Core Language Pipeline', () => {
    it('hello world compiles and runs', () => {
        const { output } = compileAndRun('show "Hello, Lume!"')
        assert.deepStrictEqual(output, ['Hello, Lume!'])
    })

    it('variables and math', () => {
        const { output } = compileAndRun('let x = 10\nlet y = 20\nshow x + y')
        assert.deepStrictEqual(output, ['30'])
    })

    it('string concatenation', () => {
        const { output } = compileAndRun('let name = "Lume"\nshow "Hello, " + name + "!"')
        assert.deepStrictEqual(output, ['Hello, Lume!'])
    })

    it('conditionals', () => {
        const { output } = compileAndRun('let x = 42\nif x > 40:\n    show "big"')
        assert.deepStrictEqual(output, ['big'])
    })

    it('show statement compiles to console.log', () => {
        const { js } = compileAndRun('show "Lume works"')
        assert.ok(js.includes('console.log'), 'show should compile to console.log')
    })
})

/* ═══ E2E: English Mode Pipeline ═══ */
describe('E2E: English Mode Resolution', () => {
    it('resolves basic English to AST nodes', async () => {
        const result = await resolveEnglishFile('mode: english\n\nget the user name\nshow the user name', { strict: false })
        assert.ok(result.ast.length >= 2, 'Should produce at least 2 AST nodes')
        const types = result.ast.map(n => n.type)
        assert.ok(types.includes('VariableAccess'), 'Should include VariableAccess')
        assert.ok(types.includes('ShowStatement'), 'Should include ShowStatement')
    })

    it('resolves CRUD operations', async () => {
        const result = await resolveEnglishFile('mode: english\n\ncreate a new task with title\nsave the task to the database\ndelete the old tasks', { strict: false })
        const types = result.ast.map(n => n.type)
        assert.ok(types.includes('CreateOperation'))
        assert.ok(types.includes('StoreOperation'))
        assert.ok(types.includes('DeleteOperation'))
    })

    it('resolves loops', async () => {
        const result = await resolveEnglishFile('mode: english\n\nrepeat 5 times\nfor each item in the list', { strict: false })
        const types = result.ast.map(n => n.type)
        assert.ok(types.includes('RepeatLoop'))
        assert.ok(types.includes('ForEachLoop'))
    })

    it('resolves math operations', async () => {
        const result = await resolveEnglishFile('mode: english\n\nadd 10 to the price\nsubtract 5 from the total', { strict: false })
        const types = result.ast.map(n => n.type)
        assert.ok(types.includes('BinaryExpression'))
    })

    it('tracks resolution stats', async () => {
        const result = await resolveEnglishFile('mode: english\n\n# a comment\nget the data\nshow the result', { strict: false })
        assert.ok(result.stats, 'Should have stats object')
        assert.ok(typeof result.stats.resolvedLines === 'number', 'Should track resolved count')
    })
})

/* ═══ E2E: Pattern Library Coverage ═══ */
describe('E2E: Pattern Library Coverage', () => {
    // Core CRUD patterns
    it('"get the profile" → VariableAccess', () => {
        const r = matchPattern('get the user profile')
        assert.ok(r.matched)
        assert.strictEqual(r.ast.type, 'VariableAccess')
    })

    it('"show the dashboard" → ShowStatement', () => {
        const r = matchPattern('show the dashboard')
        assert.ok(r.matched)
        assert.strictEqual(r.ast.type, 'ShowStatement')
    })

    it('"save the data to db" → StoreOperation', () => {
        const r = matchPattern('save the settings to the database')
        assert.ok(r.matched)
        assert.strictEqual(r.ast.type, 'StoreOperation')
    })

    it('"delete the old logs" → DeleteOperation', () => {
        const r = matchPattern('delete the old logs')
        assert.ok(r.matched)
        assert.strictEqual(r.ast.type, 'DeleteOperation')
    })

    it('"send a notification" → SendOperation', () => {
        const r = matchPattern('send a notification to the admin')
        assert.ok(r.matched)
        assert.strictEqual(r.ast.type, 'SendOperation')
    })

    // Loops
    it('"repeat 10 times" → RepeatLoop', () => {
        const r = matchPattern('repeat 10 times')
        assert.ok(r.matched)
        assert.strictEqual(r.ast.type, 'RepeatLoop')
    })

    it('"for each item in cart" → ForEachLoop', () => {
        const r = matchPattern('for each item in the cart')
        assert.ok(r.matched)
        assert.strictEqual(r.ast.type, 'ForEachLoop')
    })

    it('"while X" → WhileLoop', () => {
        const r = matchPattern('while the server is running')
        assert.ok(r.matched)
        assert.strictEqual(r.ast.type, 'WhileLoop')
    })

    // Conditionals & Variables
    it('"wait 3 seconds" → DelayStatement', () => {
        const r = matchPattern('wait 3 seconds')
        assert.ok(r.matched)
        assert.strictEqual(r.ast.type, 'DelayStatement')
    })

    it('"set count to 0" resolves', () => {
        const r = matchPattern('set the count to 0')
        assert.ok(r.matched, 'set should match a pattern')
    })

    // Math
    it('"add 5 to total" resolves', () => {
        const r = matchPattern('add 5 to the total')
        assert.ok(r.matched, 'add should match a pattern')
    })

    it('"subtract 10 from balance" → BinaryExpression', () => {
        const r = matchPattern('subtract 10 from the balance')
        assert.ok(r.matched)
    })

    // Phase 14B patterns — verify they resolve (type may vary by priority)
    it('"sort products by price" resolves', () => {
        const r = matchPattern('sort the products by price descending')
        assert.ok(r.matched, 'sort should match')
    })

    it('"return the result" → ReturnStatement', () => {
        const r = matchPattern('return the result')
        assert.ok(r.matched)
        assert.strictEqual(r.ast.type, 'ReturnStatement')
    })

    it('"increment counter by 5" → IncrementOperation', () => {
        const r = matchPattern('increment the counter by 5')
        assert.ok(r.matched)
        assert.strictEqual(r.ast.type, 'IncrementOperation')
    })

    it('"decrement lives" → DecrementOperation', () => {
        const r = matchPattern('decrement the lives by 1')
        assert.ok(r.matched)
        assert.strictEqual(r.ast.type, 'DecrementOperation')
    })

    it('"redirect to /home" → NavigateOperation', () => {
        const r = matchPattern('redirect the user to /home')
        assert.ok(r.matched)
        assert.strictEqual(r.ast.type, 'NavigateOperation')
    })

    it('"swap X and Y" → SwapOperation', () => {
        const r = matchPattern('swap the left and right panels')
        assert.ok(r.matched)
        assert.strictEqual(r.ast.type, 'SwapOperation')
    })

    it('"throw error" → ThrowStatement', () => {
        const r = matchPattern('throw an error: invalid input')
        assert.ok(r.matched)
        assert.strictEqual(r.ast.type, 'ThrowStatement')
    })

    it('"from 1 to 10" → RangeExpression', () => {
        const r = matchPattern('from 1 to 10')
        assert.ok(r.matched)
        assert.strictEqual(r.ast.type, 'RangeExpression')
    })
})

/* ═══ E2E: lume create ═══ */
describe('E2E: lume create', () => {
    it('parses app description into plan', () => {
        const result = parseAppDescription('a blog with comments and search')
        assert.ok(result, 'Should return a result object')
        assert.ok(result.plan, 'Should have a plan')
        assert.ok(result.plan.components.length > 0, 'Should have components')
        assert.ok(Object.keys(result.plan.models).length > 0, 'Should have models')
    })

    it('generates files with real content', () => {
        const result = parseAppDescription('an ecommerce store with products')
        const { files } = generateProjectStructure(result.plan)
        assert.ok(files.length >= 5, 'Should generate at least 5 files')

        // Check key files exist and have content
        const pkgJson = files.find(f => f.path === 'package.json')
        assert.ok(pkgJson, 'package.json should exist')
        assert.ok(pkgJson.content.includes('"name"'), 'package.json should have real content')

        const indexHtml = files.find(f => f.path === 'index.html')
        assert.ok(indexHtml, 'index.html should exist')
        assert.ok(indexHtml.content.includes('<!DOCTYPE html>'), 'index.html should have doctype')

        const mainJs = files.find(f => f.path === 'src/main.js')
        assert.ok(mainJs, 'main.js should exist')
        assert.ok(mainJs.content.includes('import'), 'main.js should have imports')
    })
})

/* ═══ E2E: Error Handling ═══ */
describe('E2E: Error Handling', () => {
    it('catches bad syntax', () => {
        let threw = false
        try { compileAndRun('if :') } catch { threw = true }
        assert.ok(threw, 'Bad syntax should throw')
    })
})
