// Generated by Lume Compiler
import { __lume_ask, __lume_think, __lume_generate, __lume_loadConfig } from "lume-runtime";
const __lume_config = __lume_loadConfig();

// ai_demo.lume — Demonstrates AI integration in Lume
// Simple ask — uses the default model
let answer = (await __lume_ask({ prompt: "What is the capital of France?", model: null, format: null, config: __lume_config }));
console.log(`Answer: ${answer}`);
// Think — uses analytical mode (lower temperature, system prompt)
let analysis = (await __lume_think({ prompt: "What are the pros and cons of microservices vs monoliths?", model: null, format: null, config: __lume_config }));
console.log(`Analysis: ${analysis}`);
// Generate — creative mode (higher temperature)
let poem = (await __lume_generate({ prompt: "Write a haiku about programming", model: null, format: null, config: __lume_config }));
console.log(poem);
// Model selector — use a specific model
let claude_answer = (await __lume_ask({ prompt: "Explain quantum computing in one sentence", model: "claude.sonnet", format: null, config: __lume_config }));
console.log(claude_answer);
// Structured output — parse as JSON
let data = (await __lume_ask({ prompt: "List 3 programming languages with their year of creation. Return as JSON array.", model: null, format: "json", config: __lume_config }));
console.log(data);
// Function that uses AI
async function summarize(content) {
  let summary = (await __lume_ask({ prompt: `Summarize this in one sentence: ${content}`, model: null, format: null, config: __lume_config }));
  return summary;
}
let result = summarize("The quick brown fox jumps over the lazy dog. This sentence contains every letter of the English alphabet and is known as a pangram.");
console.log(result);
