/**
 * ====== Lume Transpiler ======
 * Walks the AST and emits clean, readable JavaScript.
 * 
 * Milestone 2 additions:
 *   - if/else/else-if → if/else if/else
 *   - when/is → switch or if-else chain
 *   - to func() → function declarations
 *   - for each → for...of
 *   - for range → for (let i = ...)
 *   - while → while
 *   - break/continue → break/continue
 *   - type → class with constructor
 *   - test → wrapped test function
 *   - expect → assertion
 *   - export/use → export/import
 *   - compound assignment (+=, etc.)
 *
 * Milestone 3: AI integration (ask/think/generate)
 * Milestone 4: Interoperability (fetch, pipe, read, write, await)
 */

import { NodeType } from './parser.js'
import { compileConditionExpression } from './intent-resolver/logic-blocks.js'
import { compileStructure } from './intent-resolver/structure-parser.js'
import { compileTryCatch } from './intent-resolver/error-handling.js'
import { compileTestSuite } from './intent-resolver/test-framework.js'
import { compileEnvironmentBlock, compileEnvVariable, compileFeatureCheck } from './intent-resolver/environment.js'
import { compileParallelBlock, compileSequentialChain, compileTimerStatement } from './intent-resolver/concurrency.js'

export class Transpiler {
    constructor(ast, filename = '<stdin>') {
        this.ast = ast
        this.filename = filename
        this.output = []
        this.indentLevel = 0
        this.hasAICalls = false
        this.hasFileCalls = false
        this.hasFetchCalls = false
    }

    // ── Public API ──
    transpile() {
        // Pre-scan for AI calls
        this.hasAICalls = this._containsAICalls(this.ast)
        this.hasFileCalls = this._containsNodeType(this.ast, [NodeType.ReadExpression, NodeType.WriteExpression])
        this.hasFetchCalls = this._containsNodeType(this.ast, [NodeType.FetchExpression])
        this.hasSelfSustaining = this._containsNodeType(this.ast, [
            NodeType.MonitorBlock, NodeType.HealBlock, NodeType.OptimizeBlock, NodeType.EvolveBlock
        ])
        this.hasHealable = this._containsDecorator(this.ast, '@healable')

        this.output.push('// Generated by Lume Compiler')
        if (this.hasFileCalls) {
            this.output.push('import { readFileSync, writeFileSync } from "node:fs";')
        }
        if (this.hasSelfSustaining || this.hasHealable) {
            this.output.push('import { monitor } from "lume-runtime/monitor.js";')
            this.output.push('import { healer } from "lume-runtime/healer.js";')
            this.output.push('import { optimizer } from "lume-runtime/optimizer.js";')
            this.output.push('import { evolver } from "lume-runtime/evolver.js";')
        }
        if (this.hasAICalls) {
            this.output.push('import { __lume_ask, __lume_think, __lume_generate, __lume_loadConfig } from "lume-runtime";')
            this.output.push('const __lume_config = __lume_loadConfig();')
        }
        this.output.push('')

        for (const node of this.ast.body) {
            const lines = this._emitNode(node)
            if (lines !== null && lines !== undefined) {
                if (Array.isArray(lines)) {
                    this.output.push(...lines)
                } else {
                    this.output.push(lines)
                }
            }
        }

        return this.output.join('\n') + '\n'
    }

    // Deep check for AI node types in the AST
    _containsAICalls(node) {
        if (!node || typeof node !== 'object') return false
        if (node.type === NodeType.AskExpression || node.type === NodeType.ThinkExpression || node.type === NodeType.GenerateExpression) return true
        for (const key of Object.keys(node)) {
            const val = node[key]
            if (Array.isArray(val)) {
                if (val.some(v => this._containsAICalls(v))) return true
            } else if (typeof val === 'object' && val !== null && val.type) {
                if (this._containsAICalls(val)) return true
            }
        }
        return false
    }

    // Generic node type check
    _containsNodeType(node, types) {
        if (!node || typeof node !== 'object') return false
        if (types.includes(node.type)) return true
        for (const key of Object.keys(node)) {
            const val = node[key]
            if (Array.isArray(val)) {
                if (val.some(v => this._containsNodeType(v, types))) return true
            } else if (typeof val === 'object' && val !== null && val.type) {
                if (this._containsNodeType(val, types)) return true
            }
        }
        return false
    }

    _containsDecorator(node, decorator) {
        if (!node || typeof node !== 'object') return false
        if (node.decorator === decorator) return true
        for (const key of Object.keys(node)) {
            const val = node[key]
            if (Array.isArray(val)) {
                if (val.some(v => this._containsDecorator(v, decorator))) return true
            } else if (typeof val === 'object' && val !== null) {
                if (this._containsDecorator(val, decorator)) return true
            }
        }
        return false
    }

    _emitConfigBlock(runtimeName, node) {
        const config = JSON.stringify(node.config || {})
        return this._indent(`// Lume ${runtimeName} config\n${this._indent('')}Object.assign(${runtimeName}, ${config});`)
    }

    // ── Private: Node Emission ──
    _emitNode(node) {
        switch (node.type) {
            case NodeType.LetDeclaration: return this._emitLet(node)
            case NodeType.DefineDeclaration: return this._emitDefine(node)
            case NodeType.ShowStatement: return this._emitShow(node)
            case NodeType.LogStatement: return this._emitLog(node)
            case NodeType.SetStatement: return this._emitSet(node)
            case NodeType.ReturnStatement: return this._emitReturn(node)
            case NodeType.IfStatement: return this._emitIf(node)
            case NodeType.WhenStatement: return this._emitWhen(node)
            case NodeType.FunctionDeclaration: return this._emitFunction(node)
            case NodeType.ForEachStatement: return this._emitForEach(node)
            case NodeType.ForEachIndexStatement: return this._emitForEachIndex(node)
            case NodeType.ForRangeStatement: return this._emitForRange(node)
            case NodeType.WhileStatement: return this._emitWhile(node)
            case NodeType.BreakStatement: return this._indent('break;')
            case NodeType.ContinueStatement: return this._indent('continue;')
            case NodeType.TypeDeclaration: return this._emitTypeDeclaration(node)
            case NodeType.TestBlock: return this._emitTestBlock(node)
            case NodeType.VerifyStatement: return this._emitVerify(node)
            case NodeType.ExpectStatement: return this._emitExpect(node)
            case NodeType.ExportStatement: return this._emitExport(node)
            case NodeType.UseStatement: return this._emitUse(node)
            case NodeType.AssignmentExpression: return this._emitAssignment(node)
            case NodeType.CommentNode: return this._indent(`// ${node.value}`)
            case NodeType.ReadExpression:
                return this._indent(this._emitExpression(node) + ';')
            case NodeType.WriteExpression:
                return this._indent(this._emitWrite(node))
            case NodeType.MonitorBlock:
                return this._emitConfigBlock('monitor', node)
            case NodeType.HealBlock:
                return this._emitConfigBlock('healer', node)
            case NodeType.OptimizeBlock:
                return this._emitConfigBlock('optimizer', node)
            case NodeType.EvolveBlock:
                return this._emitConfigBlock('evolver', node)

            // ── English Mode (M7) Node Types ──
            case NodeType.VariableAccess: return this._emitVariableAccess(node)
            case NodeType.StoreOperation: return this._emitStoreOperation(node)
            case NodeType.DeleteOperation: return this._emitDeleteOperation(node)
            case NodeType.CreateOperation: return this._emitCreateOperation(node)
            case NodeType.UpdateOperation: return this._emitUpdateOperation(node)
            case NodeType.SendOperation: return this._emitSendOperation(node)
            case NodeType.FilterOperation: return this._emitFilterOperation(node)
            case NodeType.SortOperation: return this._emitSortOperation(node)
            case NodeType.ConnectionSetup: return this._emitConnectionSetup(node)
            case NodeType.EventListener: return this._emitEventListener(node)
            case NodeType.NavigateOperation: return this._emitNavigateOperation(node)
            case NodeType.DelayStatement: return this._emitDelayStatement(node)
            case NodeType.RawBlock: return this._emitRawBlock(node)
            case NodeType.HealableDecorator: return this._indent('// @healable (English Mode decorator)')

            // ── Gap 2: Compound Logic Blocks ──
            case 'CompoundIfStatement': return this._emitCompoundIf(node)

            // ── Gap 10: Structure Definitions ──
            case 'StructureDefinition': return this._emitStructureDefinition(node)

            // ── Gap 11: Try/Catch/Retry ──
            case 'TryCatchStatement': return this._emitTryCatch(node)
            case 'ThrowStatement': return this._indent(`throw new Error(${JSON.stringify(node.message)});`)

            // ── Gap 12: Test Framework ──
            case 'TestSuite': return this._emitTestSuite(node)
            case 'TestCase': return this._emitTestSuite(node)

            // ── Gap 13: Environment ──
            case 'EnvironmentBlock': return this._emitEnvironmentBlock(node)
            case 'EnvVariable': return this._emitEnvVariable(node)
            case 'FeatureCheck': return this._emitFeatureCheck(node)

            // ── Gap 14: Concurrency ──
            case 'ParallelBlock': return this._emitConcurrencyBlock(node)
            case 'RaceBlock': return this._emitConcurrencyBlock(node)
            case 'AllSettledBlock': return this._emitConcurrencyBlock(node)
            case 'SequentialChain': return this._emitSequentialChain(node)
            case 'TimerStatement': return this._emitTimerStatement(node)

            // ── Gap 15: Comments ──
            case 'CommentNode': return this._indent(node.jsOutput || `// ${node.value}`)

            default:
                // Expression statement
                return this._indent(this._emitExpression(node) + ';')
        }
    }

    // ══════════════════════════
    //  DECLARATIONS
    // ══════════════════════════

    _emitLet(node) {
        const value = this._emitExpression(node.value)
        return this._indent(`let ${node.name} = ${value};`)
    }

    _emitDefine(node) {
        const value = this._emitExpression(node.value)
        return this._indent(`const ${node.name} = ${value};`)
    }

    // ══════════════════════════
    //  SIMPLE STATEMENTS
    // ══════════════════════════

    _emitShow(node) {
        const value = this._emitExpression(node.value)
        return this._indent(`console.log(${value});`)
    }

    _emitLog(node) {
        const value = this._emitExpression(node.value)
        return this._indent(`console.log(${value});`)
    }

    _emitSet(node) {
        const value = this._emitExpression(node.value)
        return this._indent(`${node.name} = ${value};`)
    }

    _emitReturn(node) {
        if (node.value) {
            return this._indent(`return ${this._emitExpression(node.value)};`)
        }
        return this._indent('return;')
    }

    _emitAssignment(node) {
        const value = this._emitExpression(node.value)
        return this._indent(`${node.name} ${node.operator} ${value};`)
    }

    // ══════════════════════════
    //  CONTROL FLOW
    // ══════════════════════════

    _emitIf(node) {
        const lines = []
        const cond = this._emitExpression(node.condition)
        lines.push(this._indent(`if (${cond}) {`))
        this.indentLevel++
        for (const stmt of node.body) {
            const l = this._emitNode(stmt)
            if (l) lines.push(...(Array.isArray(l) ? l : [l]))
        }
        this.indentLevel--

        if (node.elseBody) {
            // Check if it's an else-if chain
            if (node.elseBody.length === 1 && node.elseBody[0].type === NodeType.IfStatement) {
                const elseIfLines = this._emitIf(node.elseBody[0])
                const elseIfArr = Array.isArray(elseIfLines) ? elseIfLines : [elseIfLines]
                // Replace "if" with "} else if"
                elseIfArr[0] = this._indent(`} else ${elseIfArr[0].trimStart()}`)
                lines.push(...elseIfArr)
            } else {
                lines.push(this._indent('} else {'))
                this.indentLevel++
                for (const stmt of node.elseBody) {
                    const l = this._emitNode(stmt)
                    if (l) lines.push(...(Array.isArray(l) ? l : [l]))
                }
                this.indentLevel--
                lines.push(this._indent('}'))
            }
        } else {
            lines.push(this._indent('}'))
        }

        return lines
    }

    _emitWhen(node) {
        const lines = []
        const subject = this._emitExpression(node.subject)

        // Check if all patterns are simple values (strings, numbers) → use switch
        const allSimple = node.cases.every(c =>
            c.pattern.type === 'string' || c.pattern.type === 'number' || c.pattern.type === 'default'
        )

        if (allSimple) {
            lines.push(this._indent(`switch (${subject}) {`))
            this.indentLevel++
            for (const c of node.cases) {
                if (c.pattern.type === 'default') {
                    lines.push(this._indent('default: {'))
                } else {
                    const val = c.pattern.type === 'string' ? JSON.stringify(c.pattern.value) : c.pattern.value
                    lines.push(this._indent(`case ${val}: {`))
                }
                this.indentLevel++
                for (const stmt of c.body) {
                    const l = this._emitNode(stmt)
                    if (l) lines.push(...(Array.isArray(l) ? l : [l]))
                }
                lines.push(this._indent('break;'))
                this.indentLevel--
                lines.push(this._indent('}'))
            }
            this.indentLevel--
            lines.push(this._indent('}'))
        } else {
            // Result pattern matching (ok/error) → if/else
            let first = true
            for (const c of node.cases) {
                if (c.pattern.type === 'ok') {
                    const prefix = first ? 'if' : '} else if'
                    lines.push(this._indent(`${prefix} (${subject}.isOk) {`))
                    this.indentLevel++
                    lines.push(this._indent(`let ${c.pattern.binding} = ${subject}.unwrap();`))
                    for (const stmt of c.body) {
                        const l = this._emitNode(stmt)
                        if (l) lines.push(...(Array.isArray(l) ? l : [l]))
                    }
                    this.indentLevel--
                } else if (c.pattern.type === 'error') {
                    lines.push(this._indent(`} else {`))
                    this.indentLevel++
                    lines.push(this._indent(`let ${c.pattern.binding} = ${subject}._error;`))
                    for (const stmt of c.body) {
                        const l = this._emitNode(stmt)
                        if (l) lines.push(...(Array.isArray(l) ? l : [l]))
                    }
                    this.indentLevel--
                    lines.push(this._indent('}'))
                } else if (c.pattern.type === 'default') {
                    lines.push(this._indent(`} else {`))
                    this.indentLevel++
                    for (const stmt of c.body) {
                        const l = this._emitNode(stmt)
                        if (l) lines.push(...(Array.isArray(l) ? l : [l]))
                    }
                    this.indentLevel--
                    lines.push(this._indent('}'))
                }
                first = false
            }
            if (!node.cases.some(c => c.pattern.type === 'error' || c.pattern.type === 'default')) {
                lines.push(this._indent('}'))
            }
        }

        return lines
    }

    // ══════════════════════════
    //  FUNCTIONS
    // ══════════════════════════

    _emitFunction(node) {
        const lines = []
        const params = node.params.map(p => p.name).join(', ')
        const isAsync = this._containsAICalls({ body: node.body })
        const prefix = isAsync ? 'async function' : 'function'
        lines.push(this._indent(`${prefix} ${node.name}(${params}) {`))
        this.indentLevel++
        for (const stmt of node.body) {
            const l = this._emitNode(stmt)
            if (l) lines.push(...(Array.isArray(l) ? l : [l]))
        }
        this.indentLevel--
        lines.push(this._indent('}'))
        return lines
    }

    // ══════════════════════════
    //  LOOPS
    // ══════════════════════════

    _emitForEach(node) {
        const lines = []
        const iterable = this._emitExpression(node.iterable)
        lines.push(this._indent(`for (const ${node.item} of ${iterable}) {`))
        this.indentLevel++
        for (const stmt of node.body) {
            const l = this._emitNode(stmt)
            if (l) lines.push(...(Array.isArray(l) ? l : [l]))
        }
        this.indentLevel--
        lines.push(this._indent('}'))
        return lines
    }

    _emitForEachIndex(node) {
        const lines = []
        const iterable = this._emitExpression(node.iterable)
        lines.push(this._indent(`for (let ${node.index} = 0; ${node.index} < ${iterable}.length; ${node.index}++) {`))
        this.indentLevel++
        lines.push(this._indent(`const ${node.item} = ${iterable}[${node.index}];`))
        for (const stmt of node.body) {
            const l = this._emitNode(stmt)
            if (l) lines.push(...(Array.isArray(l) ? l : [l]))
        }
        this.indentLevel--
        lines.push(this._indent('}'))
        return lines
    }

    _emitForRange(node) {
        const lines = []
        const start = this._emitExpression(node.start)
        const end = this._emitExpression(node.end)
        const step = node.step ? this._emitExpression(node.step) : '1'
        lines.push(this._indent(`for (let ${node.variable} = ${start}; ${node.variable} < ${end}; ${node.variable} += ${step}) {`))
        this.indentLevel++
        for (const stmt of node.body) {
            const l = this._emitNode(stmt)
            if (l) lines.push(...(Array.isArray(l) ? l : [l]))
        }
        this.indentLevel--
        lines.push(this._indent('}'))
        return lines
    }

    _emitWhile(node) {
        const lines = []
        const cond = this._emitExpression(node.condition)
        lines.push(this._indent(`while (${cond}) {`))
        this.indentLevel++
        for (const stmt of node.body) {
            const l = this._emitNode(stmt)
            if (l) lines.push(...(Array.isArray(l) ? l : [l]))
        }
        this.indentLevel--
        lines.push(this._indent('}'))
        return lines
    }

    // ══════════════════════════
    //  TYPES
    // ══════════════════════════

    _emitTypeDeclaration(node) {
        const lines = []
        if (node.isAlias) {
            // Type alias → just a comment (JS has no equivalent without TS)
            lines.push(this._indent(`// type ${node.name} = ${node.aliasType.name}`))
        } else {
            // Struct → class with constructor
            lines.push(this._indent(`class ${node.name} {`))
            this.indentLevel++
            const paramNames = node.fields.map(f => f.name).join(', ')
            lines.push(this._indent(`constructor({ ${paramNames} } = {}) {`))
            this.indentLevel++
            for (const field of node.fields) {
                if (field.defaultValue) {
                    const def = this._emitExpression(field.defaultValue)
                    lines.push(this._indent(`this.${field.name} = ${field.name} !== undefined ? ${field.name} : ${def};`))
                } else {
                    lines.push(this._indent(`this.${field.name} = ${field.name};`))
                }
            }
            this.indentLevel--
            lines.push(this._indent('}'))
            this.indentLevel--
            lines.push(this._indent('}'))
        }
        return lines
    }

    // ══════════════════════════
    //  TESTING
    // ══════════════════════════

    _emitTestBlock(node) {
        const lines = []
        lines.push(this._indent(`// TEST: ${node.name}`))
        lines.push(this._indent(`(function test_${node.name.replace(/\W+/g, '_')}() {`))
        this.indentLevel++
        lines.push(this._indent('try {'))
        this.indentLevel++
        for (const stmt of node.body) {
            const l = this._emitNode(stmt)
            if (l) lines.push(...(Array.isArray(l) ? l : [l]))
        }
        lines.push(this._indent(`console.log('  ✓ ${node.name}');`))
        this.indentLevel--
        lines.push(this._indent('} catch (e) {'))
        this.indentLevel++
        lines.push(this._indent(`console.error('  ✗ ${node.name}:', e.message);`))
        this.indentLevel--
        lines.push(this._indent('}'))
        this.indentLevel--
        lines.push(this._indent('})();'))
        return lines
    }

    _emitVerify(node) {
        const subject = this._emitExpression(node.subject)
        switch (node.assertionType) {
            case 'equals': {
                const expected = this._emitExpression(node.expected)
                return this._indent(`if (${subject} !== ${expected}) throw new Error(\`✗ Verify failed: expected \${JSON.stringify(${subject})} to equal \${JSON.stringify(${expected})}\`);`)
            }
            case 'notEquals': {
                const expected = this._emitExpression(node.expected)
                return this._indent(`if (${subject} === ${expected}) throw new Error(\`✗ Verify failed: expected \${JSON.stringify(${subject})} to NOT equal \${JSON.stringify(${expected})}\`);`)
            }
            case 'notEmpty':
                return this._indent(`if (!${subject} || (Array.isArray(${subject}) ? ${subject}.length === 0 : ${subject} === '')) throw new Error(\`✗ Verify failed: expected \${JSON.stringify(${subject})} to not be empty\`);`)
            case 'contains': {
                const expected = this._emitExpression(node.expected)
                return this._indent(`if (!(Array.isArray(${subject}) ? ${subject}.includes(${expected}) : String(${subject}).includes(${expected}))) throw new Error(\`✗ Verify failed: expected \${JSON.stringify(${subject})} to contain \${JSON.stringify(${expected})}\`);`)
            }
            case 'comparison': {
                const expected = this._emitExpression(node.expected)
                return this._indent(`if (!(${subject} ${node.operator} ${expected})) throw new Error(\`✗ Verify failed: expected \${${subject}} ${node.operator} \${${expected}}\`);`)
            }
            default:
                return this._indent(`if (!${subject}) throw new Error('✗ Verify failed: assertion is falsy');`)
        }
    }

    _emitExpect(node) {
        if (node.expected) {
            const actual = this._emitExpression(node.actual)
            const expected = this._emitExpression(node.expected)
            return this._indent(`if (${actual} !== ${expected}) throw new Error(\`Expected \${${expected}} but got \${${actual}}\`);`)
        }
        const actual = this._emitExpression(node.actual)
        return this._indent(`if (!(${actual})) throw new Error('Assertion failed');`)
    }

    // ══════════════════════════
    //  MODULES
    // ══════════════════════════

    _emitExport(node) {
        const inner = this._emitNode(node.declaration)
        if (Array.isArray(inner)) {
            inner[0] = inner[0].replace(/^(\s*)/, '$1export ')
            return inner
        }
        return inner.replace(/^(\s*)/, '$1export ')
    }

    _emitUse(node) {
        if (node.imports.length > 0) {
            const names = node.imports.join(', ')
            return this._indent(`import { ${names} } from ${JSON.stringify(node.source)};`)
        }
        if (node.alias) {
            return this._indent(`import * as ${node.alias} from ${JSON.stringify(node.source)};`)
        }
        return this._indent(`import ${JSON.stringify(node.source)};`)
    }

    // ══════════════════════════
    //  EXPRESSIONS
    // ══════════════════════════

    _emitExpression(node) {
        switch (node.type) {
            case NodeType.NumberLiteral:
                return String(node.value)

            case NodeType.StringLiteral:
                return JSON.stringify(node.value)

            case NodeType.BooleanLiteral:
                return String(node.value)

            case NodeType.NullLiteral:
                return 'null'

            case NodeType.Identifier:
                return node.name

            case NodeType.InterpolatedString:
                return this._emitInterpolatedString(node)

            case NodeType.BinaryExpression:
                return this._emitBinary(node)

            case NodeType.UnaryExpression:
                return this._emitUnary(node)

            case NodeType.MemberExpression:
                return `${this._emitExpression(node.object)}.${node.property}`

            case NodeType.IndexExpression:
                return `${this._emitExpression(node.object)}[${this._emitExpression(node.index)}]`

            case NodeType.CallExpression:
                const callee = this._emitExpression(node.callee)
                const args = node.arguments.map(a => this._emitExpression(a)).join(', ')
                return `${callee}(${args})`

            case NodeType.ListLiteral:
                const elements = node.elements.map(e => this._emitExpression(e)).join(', ')
                return `[${elements}]`

            case NodeType.MapLiteral:
                const entries = node.entries.map(e => `${e.key}: ${this._emitExpression(e.value)}`).join(', ')
                return `{ ${entries} }`

            // AI expressions
            case NodeType.AskExpression:
                return this._emitAICall('__lume_ask', node)
            case NodeType.ThinkExpression:
                return this._emitAICall('__lume_think', node)
            case NodeType.GenerateExpression:
                return this._emitAICall('__lume_generate', node)

            // Fetch expression
            case NodeType.FetchExpression:
                return this._emitFetch(node)

            // Pipe expression: a |> b → b(a)
            case NodeType.PipeExpression:
                return this._emitPipe(node)

            // Await expression
            case NodeType.AwaitExpression:
                return `(await ${this._emitExpression(node.expression)})`

            // Read expression
            case NodeType.ReadExpression:
                return `readFileSync(${this._emitExpression(node.path)}, "utf-8")`

            // Write expression
            case NodeType.WriteExpression:
                return this._emitWrite(node)

            default:
                throw new Error(`Transpiler: Unknown expression type '${node.type}'`)
        }
    }

    _emitAICall(fnName, node) {
        const prompt = this._emitExpression(node.prompt)
        const model = node.model ? JSON.stringify(node.model) : 'null'
        const format = node.outputFormat ? JSON.stringify(node.outputFormat) : 'null'
        return `(await ${fnName}({ prompt: ${prompt}, model: ${model}, format: ${format}, config: __lume_config }))`
    }

    _emitFetch(node) {
        const url = this._emitExpression(node.url)
        const method = node.method.toUpperCase()
        const format = node.outputFormat || 'json'

        if (method === 'GET' && !node.body) {
            if (format === 'json') {
                return `(await (await fetch(${url})).json())`
            }
            return `(await (await fetch(${url})).text())`
        }

        // POST/PUT/DELETE with body
        const opts = [`method: ${JSON.stringify(method)}`]
        opts.push(`headers: { "Content-Type": "application/json" }`)
        if (node.body) {
            opts.push(`body: JSON.stringify(${this._emitExpression(node.body)})`)
        }

        if (format === 'json') {
            return `(await (await fetch(${url}, { ${opts.join(', ')} })).json())`
        }
        return `(await (await fetch(${url}, { ${opts.join(', ')} })).text())`
    }

    _emitPipe(node) {
        const input = this._emitExpression(node.left)
        // If right side is a call expression, inject the left as the first argument
        if (node.right.type === NodeType.CallExpression) {
            const callee = this._emitExpression(node.right.callee)
            const existingArgs = node.right.arguments.map(a => this._emitExpression(a))
            return `${callee}(${[input, ...existingArgs].join(', ')})`
        }
        // Otherwise treat right side as a function to call with left as argument
        const fn = this._emitExpression(node.right)
        return `${fn}(${input})`
    }

    _emitWrite(node) {
        const data = this._emitExpression(node.data)
        const path = this._emitExpression(node.path)
        return `writeFileSync(${path}, ${data}, "utf-8");`
    }

    _emitInterpolatedString(node) {
        let result = '`'
        for (const part of node.parts) {
            if (part.type === NodeType.StringLiteral) {
                result += part.value.replace(/`/g, '\\`').replace(/\$/g, '\\$')
            } else {
                result += '${' + this._emitExpression(part) + '}'
            }
        }
        result += '`'
        return result
    }

    _emitBinary(node) {
        const left = this._emitExpression(node.left)
        const right = this._emitExpression(node.right)
        return `(${left} ${node.operator} ${right})`
    }

    _emitUnary(node) {
        const operand = this._emitExpression(node.operand)
        return `${node.operator}${operand}`
    }

    _indent(line) {
        return '  '.repeat(this.indentLevel) + line
    }

    // ══════════════════════════════════════
    //  ENGLISH MODE (M7) EMISSIONS
    // ══════════════════════════════════════

    _emitVariableAccess(node) {
        const target = this._sanitizeName(node.target)
        if (node.source) {
            const source = this._sanitizeName(node.source)
            return this._indent(`const ${target} = await db.query('SELECT * FROM ${source} WHERE id = ?', [${target}_id]);`)
        }
        return this._indent(`const ${target}_data = ${target};`)
    }

    _emitStoreOperation(node) {
        const value = this._sanitizeName(node.value)
        const target = this._sanitizeName(node.target || 'database')
        return this._indent(`await db.insert('${target}', ${value});`)
    }

    _emitDeleteOperation(node) {
        const target = this._sanitizeName(node.target)
        if (node.source) {
            const source = this._sanitizeName(node.source)
            return this._indent(`await db.delete('${source}', { where: { id: ${target}_id } });`)
        }
        return this._indent(`await db.delete('${target}');`)
    }

    _emitCreateOperation(node) {
        const target = this._sanitizeName(node.target)
        const fields = (node.fields || []).map(f => `${f}: null`).join(', ')
        if (fields) {
            return this._indent(`const ${target} = await db.create('${target}', { ${fields} });`)
        }
        return this._indent(`const ${target} = await db.create('${target}', {});`)
    }

    _emitUpdateOperation(node) {
        const target = this._sanitizeName(node.target)
        if (node.value) {
            return this._indent(`await db.update('${target}', { value: ${JSON.stringify(node.value)} });`)
        }
        return this._indent(`await db.update('${target}', {});`)
    }

    _emitSendOperation(node) {
        const payload = this._sanitizeName(node.payload)
        if (node.target) {
            return this._indent(`await fetch(${JSON.stringify(node.target)}, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(${payload}) });`)
        }
        return this._indent(`emit(${JSON.stringify(payload)}, ${payload});`)
    }

    _emitFilterOperation(node) {
        const target = this._sanitizeName(node.target)
        if (node.condition) {
            return this._indent(`const filtered_${target} = ${target}.filter(item => ${this._naturalConditionToJS(node.condition)});`)
        }
        return this._indent(`const filtered_${target} = ${target}.filter(Boolean);`)
    }

    _emitSortOperation(node) {
        const target = this._sanitizeName(node.target)
        const order = node.order === 'desc' ? -1 : 1
        if (node.by) {
            const by = this._sanitizeName(node.by)
            return this._indent(`${target}.sort((a, b) => ${order === -1 ? '(b.' + by + ' > a.' + by + ' ? 1 : -1)' : '(a.' + by + ' > b.' + by + ' ? 1 : -1)'});`)
        }
        return this._indent(`${target}.sort(${order === -1 ? '(a, b) => (b > a ? 1 : -1)' : ''});`)
    }

    _emitConnectionSetup(node) {
        return this._indent(`const connection = await connect(${JSON.stringify(node.target)});`)
    }

    _emitEventListener(node) {
        const element = this._sanitizeName(node.element)
        const event = node.event || 'click'
        const lines = []
        lines.push(this._indent(`document.querySelector('#${element}').addEventListener('${event}', (event) => {`))
        this.indentLevel++
        lines.push(this._indent('// Handler code'))
        this.indentLevel--
        lines.push(this._indent('});'))
        return lines
    }

    _emitNavigateOperation(node) {
        const target = node.target
        if (target.startsWith('http') || target.startsWith('/')) {
            return this._indent(`window.location.href = ${JSON.stringify(target)};`)
        }
        return this._indent(`navigate(${JSON.stringify(target)});`)
    }

    _emitDelayStatement(node) {
        const ms = node.duration || 1000
        return this._indent(`await new Promise(resolve => setTimeout(resolve, ${ms}));`)
    }

    _emitRawBlock(node) {
        // Raw JavaScript passthrough — no transformation
        const lines = node.code.split('\n').map(l => this._indent(l))
        return lines
    }

    // ══════════════════════════════════════
    //  GAP 2: COMPOUND LOGIC BLOCKS
    // ══════════════════════════════════════

    _emitCompoundIf(node) {
        const lines = []
        let conditionExpr = compileConditionExpression(node.conditions, node.mode)
        if (node.negated) conditionExpr = `!(${conditionExpr})`

        lines.push(this._indent(`if (${conditionExpr}) {`))
        this.indentLevel++
        // Emit body — body lines are strings (English instructions resolved elsewhere)
        for (const bodyLine of (node.body || [])) {
            if (typeof bodyLine === 'string') {
                lines.push(this._indent(`// ${bodyLine}`))
            } else {
                const l = this._emitNode(bodyLine)
                if (l) lines.push(...(Array.isArray(l) ? l : [l]))
            }
        }
        this.indentLevel--

        // Else-if blocks
        if (node.elseIf) {
            for (const elseIf of node.elseIf) {
                const elseCondExpr = elseIf.condition.negated
                    ? `!(${this._naturalConditionToJS(elseIf.condition.expression)})`
                    : this._naturalConditionToJS(elseIf.condition.expression)
                lines.push(this._indent(`} else if (${elseCondExpr}) {`))
                this.indentLevel++
                for (const b of (elseIf.body || [])) {
                    if (typeof b === 'string') lines.push(this._indent(`// ${b}`))
                    else { const l = this._emitNode(b); if (l) lines.push(...(Array.isArray(l) ? l : [l])) }
                }
                this.indentLevel--
            }
        }

        // Else block
        if (node.else) {
            lines.push(this._indent('} else {'))
            this.indentLevel++
            for (const b of (node.else.body || [])) {
                if (typeof b === 'string') lines.push(this._indent(`// ${b}`))
                else { const l = this._emitNode(b); if (l) lines.push(...(Array.isArray(l) ? l : [l])) }
            }
            this.indentLevel--
            lines.push(this._indent('}'))
        } else {
            lines.push(this._indent('}'))
        }

        return lines
    }

    _sanitizeName(name) {
        if (!name) return '_unnamed'
        return name.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^(\d)/, '_$1')
    }

    _naturalConditionToJS(condition) {
        if (!condition) return 'true'
        // Convert natural language conditions to JS expressions
        return condition
            .replace(/\b(is|equals?)\b/gi, '===')
            .replace(/\b(is not|isn'?t|does not equal)\b/gi, '!==')
            .replace(/\b(greater than|more than|above|over)\b/gi, '>')
            .replace(/\b(less than|fewer than|below|under)\b/gi, '<')
            .replace(/\b(at least|>=)\b/gi, '>=')
            .replace(/\b(at most|<=)\b/gi, '<=')
            .replace(/\b(and)\b/gi, '&&')
            .replace(/\b(or)\b/gi, '||')
            .replace(/\b(not|!)\b/gi, '!')
            .replace(/\b(contains|includes)\b/gi, '.includes')
            .replace(/\b(starts with)\b/gi, '.startsWith')
            .replace(/\b(ends with)\b/gi, '.endsWith')
            .replace(/\b(exists|defined|truthy)\b/gi, '!== undefined')
            .replace(/\b(empty|blank)\b/gi, '.length === 0')
            .replace(/\b(true)\b/gi, 'true')
            .replace(/\b(false)\b/gi, 'false')
            .trim()
    }

    // ── Gap 10: Structure Definitions ──
    _emitStructureDefinition(node) {
        const code = compileStructure(node)
        for (const line of code.split('\n')) {
            this.output.push(this._indent(line).trimEnd())
        }
    }

    // ── Gap 11: Try/Catch/Retry ──
    _emitTryCatch(node) {
        const code = compileTryCatch(node)
        for (const line of code.split('\n')) {
            this.output.push(this._indent(line).trimEnd())
        }
    }

    // ── Gap 12: Test Suite ──
    _emitTestSuite(node) {
        const code = compileTestSuite(node)
        for (const line of code.split('\n')) {
            this.output.push(this._indent(line).trimEnd())
        }
    }

    // ── Gap 13: Environment ──
    _emitEnvironmentBlock(node) {
        const code = compileEnvironmentBlock(node)
        for (const line of code.split('\n')) {
            this.output.push(this._indent(line).trimEnd())
        }
    }

    _emitEnvVariable(node) {
        const code = compileEnvVariable(node)
        for (const line of code.split('\n')) {
            this.output.push(this._indent(line).trimEnd())
        }
    }

    _emitFeatureCheck(node) {
        const code = compileFeatureCheck(node)
        for (const line of code.split('\n')) {
            this.output.push(this._indent(line).trimEnd())
        }
    }

    // ── Gap 14: Concurrency ──
    _emitConcurrencyBlock(node) {
        const code = compileParallelBlock(node)
        for (const line of code.split('\n')) {
            this.output.push(this._indent(line).trimEnd())
        }
    }

    _emitSequentialChain(node) {
        const code = compileSequentialChain(node)
        for (const line of code.split('\n')) {
            this.output.push(this._indent(line).trimEnd())
        }
    }

    _emitTimerStatement(node) {
        const code = compileTimerStatement(node)
        for (const line of code.split('\n')) {
            this.output.push(this._indent(line).trimEnd())
        }
    }
}

// ── Convenience function ──
export function transpile(ast, filename) {
    return new Transpiler(ast, filename).transpile()
}
