/**
 * ═══════════════════════════════════════════════════════════
 *  Lume Transpiler — Comprehensive Test Suite
 *  Tests JavaScript code generation for all AST node types:
 *    declarations → JS let/const, control flow → if/switch,
 *    functions → function/async function, loops → for/while,
 *    types → class, modules → import/export, and more.
 * ═══════════════════════════════════════════════════════════
 */

import { describe, it } from 'node:test'
import assert from 'node:assert/strict'
import { tokenize } from '../../src/lexer.js'
import { Parser } from '../../src/parser.js'
import { Transpiler } from '../../src/transpiler.js'

// Helper — takes Lume code, returns compiled JavaScript
function compile(code) {
    const tokens = tokenize(code)
    const parser = new Parser(tokens, '<test>')
    const ast = parser.parse()
    const transpiler = new Transpiler(ast, '<test>')
    return transpiler.transpile()
}

// ══════════════════════════════════════
//  Header
// ══════════════════════════════════════

describe('Transpiler: Header', () => {
    it('includes "Generated by Lume Compiler" header', () => {
        const js = compile('let x = 1')
        assert.ok(js.includes('Generated by Lume Compiler'))
    })
    it('output is a string', () => {
        const js = compile('let x = 1')
        assert.equal(typeof js, 'string')
    })
    it('ends with newline', () => {
        const js = compile('let x = 1')
        assert.ok(js.endsWith('\n'))
    })
})

// ══════════════════════════════════════
//  Declarations
// ══════════════════════════════════════

describe('Transpiler: LetDeclaration', () => {
    it('emits let with number', () => {
        const js = compile('let x = 42')
        assert.ok(js.includes('let x = 42;'))
    })
    it('emits let with string', () => {
        const js = compile('let name = "Alice"')
        assert.ok(js.includes('let name = "Alice";'))
    })
    it('emits let with boolean', () => {
        const js = compile('let active = true')
        assert.ok(js.includes('let active = true;'))
    })
    it('emits let with null', () => {
        const js = compile('let empty = null')
        assert.ok(js.includes('let empty = null;'))
    })
    it('emits let with list', () => {
        const js = compile('let items = [1, 2, 3]')
        assert.ok(js.includes('[1, 2, 3]'))
    })
    it('emits let with map', () => {
        const js = compile('let obj = { name: "Alice" }')
        assert.ok(js.includes('name: "Alice"'))
    })
})

describe('Transpiler: DefineDeclaration', () => {
    it('emits const for define', () => {
        const js = compile('define MAX = 100')
        assert.ok(js.includes('const MAX = 100;'))
    })
})

// ══════════════════════════════════════
//  Simple Statements
// ══════════════════════════════════════

describe('Transpiler: ShowStatement', () => {
    it('emits console.log for show', () => {
        const js = compile('show "hello"')
        assert.ok(js.includes('console.log("hello");'))
    })
    it('emits console.log for show with expression', () => {
        const js = compile('show 1 + 2')
        assert.ok(js.includes('console.log'))
    })
})

describe('Transpiler: LogStatement', () => {
    it('emits console.log for log', () => {
        const js = compile('log "debug"')
        assert.ok(js.includes('console.log("debug");'))
    })
})

describe('Transpiler: SetStatement', () => {
    it('emits assignment for set', () => {
        const js = compile('set x to 10')
        assert.ok(js.includes('x = 10;'))
    })
})

describe('Transpiler: ReturnStatement', () => {
    it('emits return with value', () => {
        const js = compile('return 42')
        assert.ok(js.includes('return 42;'))
    })
    it('emits bare return', () => {
        const js = compile('return\n')
        assert.ok(js.includes('return;'))
    })
})

describe('Transpiler: AssignmentExpression', () => {
    it('emits +=', () => {
        const js = compile('x += 1')
        assert.ok(js.includes('x += 1;'))
    })
    it('emits -=', () => {
        const js = compile('x -= 5')
        assert.ok(js.includes('x -= 5;'))
    })
    it('emits *=', () => {
        const js = compile('x *= 2')
        assert.ok(js.includes('x *= 2;'))
    })
    it('emits /=', () => {
        const js = compile('x /= 3')
        assert.ok(js.includes('x /= 3;'))
    })
})

// ══════════════════════════════════════
//  Control Flow
// ══════════════════════════════════════

describe('Transpiler: IfStatement', () => {
    it('emits if block', () => {
        const js = compile('if true:\n    show "yes"')
        assert.ok(js.includes('if (true)'))
        assert.ok(js.includes('{'))
        assert.ok(js.includes('}'))
    })
    it('emits if/else', () => {
        const js = compile('if true:\n    show "a"\nelse:\n    show "b"')
        assert.ok(js.includes('} else {'))
    })
    it('emits else if chain', () => {
        const js = compile('if x is 1:\n    show "a"\nelse if x is 2:\n    show "b"')
        assert.ok(js.includes('else if'))
    })
    it('compiles is to ==', () => {
        const js = compile('if x is 1:\n    show "yes"')
        assert.ok(js.includes('=='))
    })
    it('compiles is not to !=', () => {
        const js = compile('if x is not null:\n    show "exists"')
        assert.ok(js.includes('!='))
    })
    it('compiles is greater than to >', () => {
        const js = compile('if x is greater than 5:\n    show "big"')
        assert.ok(js.includes('>'))
    })
    it('compiles is less than to <', () => {
        const js = compile('if x is less than 0:\n    show "neg"')
        assert.ok(js.includes('<'))
    })
    it('compiles is at least to >=', () => {
        const js = compile('if x is at least 10:\n    show "ok"')
        assert.ok(js.includes('>='))
    })
    it('compiles is at most to <=', () => {
        const js = compile('if x is at most 100:\n    show "ok"')
        assert.ok(js.includes('<='))
    })
})

// ══════════════════════════════════════
//  Functions
// ══════════════════════════════════════

describe('Transpiler: FunctionDeclaration', () => {
    it('emits function keyword', () => {
        const js = compile('to greet(name):\n    show name')
        assert.ok(js.includes('function greet(name)'))
    })
    it('emits multiple params', () => {
        const js = compile('to add(a, b):\n    return a')
        assert.ok(js.includes('function add(a, b)'))
    })
    it('emits function body', () => {
        const js = compile('to hello():\n    show "hi"')
        assert.ok(js.includes('function hello()'))
        assert.ok(js.includes('console.log("hi")'))
    })
})

// ══════════════════════════════════════
//  Loops
// ══════════════════════════════════════

describe('Transpiler: ForEachStatement', () => {
    it('emits for...of', () => {
        const js = compile('for each item in items:\n    show item')
        assert.ok(js.includes('for (const item of items)'))
    })
})

describe('Transpiler: ForEachIndexStatement', () => {
    it('emits indexed for loop', () => {
        const js = compile('for each item, i in items:\n    show i')
        assert.ok(js.includes('for (let i = 0;'))
    })
})

describe('Transpiler: ForRangeStatement', () => {
    it('emits for loop with range', () => {
        const js = compile('for i in 0 to 10:\n    show i')
        assert.ok(js.includes('for (let i = 0; i < 10;'))
    })
    it('emits step', () => {
        const js = compile('for i in 0 to 100 by 5:\n    show i')
        assert.ok(js.includes('+= 5'))
    })
})

describe('Transpiler: WhileStatement', () => {
    it('emits while loop', () => {
        const js = compile('while true:\n    show "x"')
        assert.ok(js.includes('while (true)'))
    })
})

describe('Transpiler: Break/Continue', () => {
    it('emits break', () => {
        const js = compile('break')
        assert.ok(js.includes('break;'))
    })
    it('emits continue', () => {
        const js = compile('continue')
        assert.ok(js.includes('continue;'))
    })
})

// ══════════════════════════════════════
//  Types
// ══════════════════════════════════════

describe('Transpiler: TypeDeclaration', () => {
    it('emits class for type', () => {
        const js = compile('type User:\n    name: text\n    age: number')
        assert.ok(js.includes('class User'))
        assert.ok(js.includes('constructor'))
    })
    it('emits comment for type alias', () => {
        const js = compile('type Score = number')
        assert.ok(js.includes('// type Score'))
    })
    it('includes field assignments', () => {
        const js = compile('type User:\n    name: text\n    age: number')
        assert.ok(js.includes('this.name'))
        assert.ok(js.includes('this.age'))
    })
})

// ══════════════════════════════════════
//  Testing
// ══════════════════════════════════════

describe('Transpiler: TestBlock', () => {
    it('emits test wrapper', () => {
        const js = compile('test "addition":\n    show 1 + 1')
        assert.ok(js.includes('TEST: addition'))
    })
    it('emits try/catch', () => {
        const js = compile('test "x":\n    show "y"')
        assert.ok(js.includes('try {'))
        assert.ok(js.includes('catch'))
    })
    it('emits pass indicator', () => {
        const js = compile('test "pass":\n    show "yes"')
        assert.ok(js.includes('✓'))
    })
})

// ══════════════════════════════════════
//  Modules
// ══════════════════════════════════════

describe('Transpiler: UseStatement', () => {
    it('emits import for use', () => {
        const js = compile('use "stdlib"')
        assert.ok(js.includes('import "stdlib";'))
    })
    it('emits named import with alias', () => {
        const js = compile('use "math" as m')
        assert.ok(js.includes('import * as m from "math";'))
    })
    it('emits destructured import', () => {
        const js = compile('use { sin, cos } from "math"')
        assert.ok(js.includes('import { sin, cos } from "math";'))
    })
})

describe('Transpiler: ExportStatement', () => {
    it('emits export prefix', () => {
        const js = compile('export let x = 1')
        assert.ok(js.includes('export let x = 1;'))
    })
})

// ══════════════════════════════════════
//  Expressions
// ══════════════════════════════════════

describe('Transpiler: Expressions', () => {
    it('emits binary +', () => {
        const js = compile('let x = 1 + 2')
        assert.ok(js.includes('(1 + 2)'))
    })
    it('emits binary -', () => {
        const js = compile('let x = 10 - 3')
        assert.ok(js.includes('(10 - 3)'))
    })
    it('emits binary *', () => {
        const js = compile('let x = 4 * 5')
        assert.ok(js.includes('(4 * 5)'))
    })
    it('emits binary /', () => {
        const js = compile('let x = 10 / 2')
        assert.ok(js.includes('(10 / 2)'))
    })
    it('emits member access', () => {
        const js = compile('let x = obj.name')
        assert.ok(js.includes('obj.name'))
    })
    it('emits index access', () => {
        const js = compile('let x = items[0]')
        assert.ok(js.includes('items[0]'))
    })
    it('emits function call', () => {
        const js = compile('let x = foo(1, 2)')
        assert.ok(js.includes('foo(1, 2)'))
    })
    it('emits interpolated string as template literal', () => {
        const js = compile('let x = "hello {name}"')
        assert.ok(js.includes('`'))
        assert.ok(js.includes('${'))
    })
    it('emits unary negation', () => {
        const js = compile('let x = -5')
        assert.ok(js.includes('-5'))
    })
})

// ══════════════════════════════════════
//  Comments
// ══════════════════════════════════════

describe('Transpiler: Comments', () => {
    it('emits // comment', () => {
        const js = compile('// this is a comment')
        assert.ok(js.includes('// '))
    })
})

// ══════════════════════════════════════
//  Pipe Expressions
// ══════════════════════════════════════

describe('Transpiler: PipeExpression', () => {
    it('emits pipe as function call', () => {
        const js = compile('let x = data |> transform')
        assert.ok(js.includes('transform(data)'))
    })
})

// ══════════════════════════════════════
//  Integration: Full Pipeline
// ══════════════════════════════════════

describe('Transpiler: Full Pipeline Integration', () => {
    it('compiles a complete program', () => {
        const code = `let name = "Alice"
let count = 0
show "Hello, {name}!"
if count is 0:
    show "empty"`
        const js = compile(code)
        assert.ok(js.includes('let name = "Alice"'))
        assert.ok(js.includes('let count = 0'))
        assert.ok(js.includes('console.log'))
        assert.ok(js.includes('if'))
    })
    it('compiles function with loop', () => {
        const code = `to sum_list(items):
    let total = 0
    for each item in items:
        set total to total
    return total`
        const js = compile(code)
        assert.ok(js.includes('function sum_list(items)'))
        assert.ok(js.includes('for (const item of items)'))
        assert.ok(js.includes('return total'))
    })
    it('compiles type + function', () => {
        const code = `type Point:
    x: number
    y: number

to distance(p):
    return p.x`
        const js = compile(code)
        assert.ok(js.includes('class Point'))
        assert.ok(js.includes('function distance(p)'))
    })
})
